name: CI - DEV

on:
  push:
    branches:
    - dev

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: yarn
    - run: CI=false yarn build:dev
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:social-connect-now
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
